---
- name: upload
  hosts: all
  gather_facts: False

  tasks:
 
  - name: '上傳配置'
    shell: cd /tmp;
           git clone https://github.com/yeyiru/NTU_IoT_Project2.git;
           cp ./client_tcp.ovpn ./client_tcp_backup.ovpn;
           cp ./NTU_IoT_Project2/clinet_tcp_new.ovpn ./clinet_tcp.ovpn;
           sudo reboot